/*
 * GENERATED by tools/schema-hints/generate.js from schema/menu.schema.json and tools/schema-hints/overrides.json. Do not edit by hand:
 * change the schema or the overrides and run `node tools/schema-hints/generate.js` (CI fails if this file is stale).
 *
 * What the Menu Editor's forms know about each part of a menu: its fields, their types, allowed values and limits.
 */
(function (root, factory) {
    var api = factory();
    if (typeof module === 'object' && module.exports) {
        module.exports = api;
    } else {
        root.DiscMenusSchemaHints = api;
    }
})(typeof self !== 'undefined' ? self : this, function () {
    'use strict';
    return {
      "kinds": {
        "audio": {
          "fields": [
            {
              "name": "music",
              "type": "object",
              "kind": "music",
              "requireAll": [
                "source"
              ],
              "description": "Background music, looped with fades. It keeps playing across menus that name the same track. source 'none' silences it for a menu.",
              "label": "Background music",
              "create": {
                "source": "themeSong"
              }
            },
            {
              "name": "sounds",
              "type": "object",
              "kind": "sounds",
              "description": "Button sounds. 'preset' picks built-in synthesized sounds (no files needed); move/select/back can each be replaced by an audio file.",
              "label": "Button sounds",
              "create": {
                "preset": "click"
              }
            }
          ],
          "title": "Music and sounds"
        },
        "background": {
          "fields": [
            {
              "name": "source",
              "required": true,
              "type": "enum",
              "enum": [
                "jellyfin",
                "tmdb",
                "fanart",
                "color",
                "image",
                "trailer"
              ],
              "label": "Where the picture comes from"
            },
            {
              "name": "imageType",
              "type": "enum",
              "enum": [
                "Primary",
                "Art",
                "Backdrop",
                "Banner",
                "Logo",
                "Thumb",
                "Disc",
                "Box",
                "Screenshot",
                "Menu",
                "BoxRear"
              ],
              "description": "For source=jellyfin: which of the parent item's images to use.",
              "label": "Which of the title's pictures",
              "appliesTo": [
                "jellyfin"
              ]
            },
            {
              "name": "index",
              "type": "integer",
              "minimum": 0,
              "description": "Image index for multi-image types (e.g. backdrop #2).",
              "label": "Picture number (when there are several)",
              "appliesTo": [
                "jellyfin"
              ],
              "default": 0
            },
            {
              "name": "tmdbFilePath",
              "type": "string",
              "pattern": "^/[A-Za-z0-9_-]+\\.(jpg|png)$",
              "description": "For source=tmdb: the TMDB file_path of a backdrop, e.g. /abc123.jpg. Jellyfin's TheMovieDb provider lists them: GET /Items/{id}/RemoteImages?type=Backdrop&providerName=TheMovieDb.",
              "label": "TMDB picture",
              "appliesTo": [
                "tmdb"
              ],
              "placeholder": "/abc123.jpg"
            },
            {
              "name": "tmdbSize",
              "type": "enum",
              "enum": [
                "w780",
                "w1280",
                "original"
              ],
              "description": "For source=tmdb: image size to fetch from TMDB's image server (default w1280). 'original' can be several megabytes.",
              "label": "TMDB picture size",
              "appliesTo": [
                "tmdb"
              ],
              "default": "w1280"
            },
            {
              "name": "fanartId",
              "type": "string",
              "pattern": "^[0-9]{1,12}$",
              "description": "For source=fanart: the numeric id of an image in fanart.tv's listing for the title (1 to 12 digits). The Jellyfin server looks it up with its administrator's fanart.tv API key and serves it, so viewers never contact fanart.tv; without a key, or for an unknown id, the page shows plain dark. List a library title's ids with GET /DiscMenus/Fanart/List/{itemId}.",
              "label": "fanart.tv picture id",
              "appliesTo": [
                "fanart"
              ],
              "control": "fanart"
            },
            {
              "name": "image",
              "type": "string",
              "format": "imageRef",
              "maxLength": 20000,
              "pattern": "^(https://[^\\s\"'()<>\\\\]+|data:image/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+|asset:[A-Za-z0-9][A-Za-z0-9._-]{0,63}(/[A-Za-z0-9][A-Za-z0-9._-]{0,63}){0,3})$",
              "description": "For source=image: the picture to use (https URL, data: URI, or asset: reference).",
              "label": "Picture",
              "appliesTo": [
                "image"
              ]
            },
            {
              "name": "trailerIndex",
              "type": "integer",
              "minimum": 0,
              "maximum": 9,
              "description": "For source=trailer: which of the item's trailers to use, 0-based (default 0). Local trailer files come first, then the YouTube trailers Jellyfin has stored for the item.",
              "label": "Which trailer (0 is the first)",
              "appliesTo": [
                "trailer"
              ],
              "default": 0
            },
            {
              "name": "muted",
              "type": "boolean",
              "description": "For source=trailer: play without sound (default true). Browsers may refuse unmuted autoplay.",
              "label": "Muted",
              "appliesTo": [
                "trailer"
              ],
              "default": true
            },
            {
              "name": "poster",
              "type": "string",
              "format": "imageRef",
              "maxLength": 20000,
              "pattern": "^(https://[^\\s\"'()<>\\\\]+|data:image/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+|asset:[A-Za-z0-9][A-Za-z0-9._-]{0,63}(/[A-Za-z0-9][A-Za-z0-9._-]{0,63}){0,3})$",
              "description": "For source=trailer: picture shown until the video is playing, and kept if the item has no usable trailer or embedding is blocked.",
              "label": "Picture shown before the trailer plays",
              "appliesTo": [
                "trailer"
              ]
            },
            {
              "name": "color",
              "type": "string",
              "pattern": "^#[0-9a-fA-F]{6}$",
              "description": "For source=color, or as a fallback tint.",
              "label": "Colour",
              "appliesTo": [
                "*"
              ],
              "defaultValue": "#000000",
              "format": "color"
            },
            {
              "name": "dim",
              "type": "number",
              "minimum": 0,
              "maximum": 1,
              "description": "Overlay darkening, 0 to 1, for label legibility.",
              "label": "Darkening (0 to 1)",
              "default": 0.4,
              "step": 0.05
            }
          ],
          "requiredWhen": {
            "field": "source",
            "values": {
              "tmdb": [
                "tmdbFilePath"
              ],
              "fanart": [
                "fanartId"
              ],
              "color": [
                "color"
              ],
              "image": [
                "image"
              ],
              "jellyfin": [
                "imageType"
              ]
            }
          },
          "title": "Background"
        },
        "document": {
          "fields": [
            {
              "name": "root",
              "required": true,
              "type": "string",
              "format": "key",
              "pattern": "^[a-z0-9][a-z0-9_-]{0,63}$",
              "description": "Key of the menu shown first.",
              "label": "Menu shown first",
              "control": "menuKey"
            },
            {
              "name": "match",
              "required": true,
              "type": "object",
              "kind": "match",
              "description": "Identifies the parent item via Jellyfin's metadata match, not files. At least one provider ID is required.",
              "label": "Which title this is for"
            },
            {
              "name": "meta",
              "type": "object",
              "kind": "meta",
              "label": "About this menu",
              "create": {}
            },
            {
              "name": "background",
              "type": "object",
              "kind": "background",
              "description": "Image references only; images are fetched locally at render time and never stored in the shared file.",
              "label": "Default background (for every page)",
              "create": {
                "source": "jellyfin",
                "imageType": "Backdrop",
                "dim": 0.4
              }
            },
            {
              "name": "theme",
              "type": "object",
              "kind": "theme",
              "label": "Colours and text (for every page)",
              "create": {
                "id": "list-dark"
              }
            },
            {
              "name": "audio",
              "type": "object",
              "kind": "audio",
              "description": "Default music and button sounds for every menu. A menu's own audio overrides it per part (its music replaces the default music, its sounds replace the default sounds). Nothing plays unless this is set.",
              "label": "Music and sounds (for every page)",
              "create": {}
            },
            {
              "name": "layout",
              "type": "object",
              "kind": "layout",
              "description": "Default layout for every menu. A menu's own layout overrides it field by field, so submenus can share the main menu's banner and style without repeating it.",
              "label": "Layout (for every page)",
              "create": {}
            },
            {
              "name": "menuId",
              "required": true,
              "type": "string",
              "description": "Stable UUID for this menu across revisions. Bindings reference it.",
              "hidden": true
            },
            {
              "name": "revision",
              "required": true,
              "type": "integer",
              "minimum": 1,
              "description": "Monotonic revision number. Bump on any change to extras or menus.",
              "hidden": true
            },
            {
              "name": "extras",
              "required": true,
              "type": "map",
              "kind": "extra",
              "minProperties": 0,
              "description": "Extras this release is expected to contain, keyed by a menu-local key. Entries reference these keys; each is resolved once to a local item in the binding file.",
              "hidden": true
            },
            {
              "name": "menus",
              "required": true,
              "type": "map",
              "kind": "menu",
              "minProperties": 1,
              "hidden": true
            }
          ],
          "title": "Whole menu"
        },
        "entry": {
          "fields": [
            {
              "name": "action",
              "required": true,
              "type": "enum",
              "enum": [
                "playFeature",
                "playExtra",
                "playSequence",
                "submenu",
                "chapters",
                "back",
                "home"
              ],
              "label": "What it does"
            },
            {
              "name": "label",
              "required": true,
              "type": "string",
              "format": "label",
              "minLength": 1,
              "maxLength": 80,
              "pattern": "^[^<>]*$",
              "description": "Plain text only. Renderers MUST insert as text (textContent), never as HTML.",
              "label": "Text on the button"
            },
            {
              "name": "extra",
              "required": true,
              "type": "string",
              "format": "key",
              "pattern": "^[a-z0-9][a-z0-9_-]{0,63}$",
              "label": "Extra to play",
              "control": "extraKey"
            },
            {
              "name": "extras",
              "required": true,
              "type": "array",
              "itemType": "string",
              "itemFormat": "key",
              "minItems": 2,
              "label": "Extras to play, in order",
              "control": "extraKeys"
            },
            {
              "name": "menu",
              "required": true,
              "type": "string",
              "format": "key",
              "pattern": "^[a-z0-9][a-z0-9_-]{0,63}$",
              "label": "Page to open",
              "control": "menuKey"
            },
            {
              "name": "startChapter",
              "type": "integer",
              "minimum": 1,
              "label": "Start at chapter"
            },
            {
              "name": "perPage",
              "type": "integer",
              "minimum": 1,
              "maximum": 24,
              "description": "Most chapter buttons per page (default 6).",
              "label": "Scenes per page",
              "default": 6
            },
            {
              "name": "style",
              "type": "enum",
              "enum": [
                "text",
                "frame",
                "glow",
                "arrow"
              ],
              "description": "How a button looks and how its highlight is drawn: plain text, an outline frame, a glow, or a pointer arrow beside the label.",
              "label": "Look of the button"
            },
            {
              "name": "position",
              "type": "object",
              "kind": "position",
              "description": "Where an element sits, as percentages of the menu screen so layouts scale to any display. x/y place the element's anchor point; w/h optionally size it.",
              "label": "Place on the screen",
              "create": {
                "x": 10,
                "y": 10
              }
            },
            {
              "name": "image",
              "type": "string",
              "format": "imageRef",
              "maxLength": 20000,
              "pattern": "^(https://[^\\s\"'()<>\\\\]+|data:image/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+|asset:[A-Za-z0-9][A-Za-z0-9._-]{0,63}(/[A-Za-z0-9][A-Za-z0-9._-]{0,63}){0,3})$",
              "description": "Artwork for a button. Never a file path. Either an https URL, a small inline data: URI for icons, or an asset:<folder>/<file> reference naming a file in the server's menu assets folder (the menu's own art, served by the plugin). Renderers draw it only via an image element, never as markup.",
              "label": "Picture for the button"
            },
            {
              "name": "imageFocus",
              "type": "string",
              "format": "imageRef",
              "maxLength": 20000,
              "pattern": "^(https://[^\\s\"'()<>\\\\]+|data:image/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+|asset:[A-Za-z0-9][A-Za-z0-9._-]{0,63}(/[A-Za-z0-9][A-Za-z0-9._-]{0,63}){0,3})$",
              "description": "Artwork for a button. Never a file path. Either an https URL, a small inline data: URI for icons, or an asset:<folder>/<file> reference naming a file in the server's menu assets folder (the menu's own art, served by the plugin). Renderers draw it only via an image element, never as markup.",
              "label": "Picture when highlighted"
            }
          ],
          "discriminator": "action",
          "variants": {
            "playFeature": {
              "title": "Play the main feature, optionally from a chapter",
              "fields": [
                "position",
                "style",
                "image",
                "imageFocus",
                "startChapter",
                "label"
              ],
              "required": [
                "label"
              ]
            },
            "playExtra": {
              "title": "Play one extra",
              "fields": [
                "position",
                "style",
                "image",
                "imageFocus",
                "extra",
                "label"
              ],
              "required": [
                "extra",
                "label"
              ]
            },
            "playSequence": {
              "title": "Play several extras in order (a 'Play All')",
              "fields": [
                "position",
                "style",
                "image",
                "imageFocus",
                "extras",
                "label"
              ],
              "required": [
                "extras",
                "label"
              ]
            },
            "submenu": {
              "title": "Open another menu",
              "fields": [
                "position",
                "style",
                "image",
                "imageFocus",
                "menu",
                "label"
              ],
              "required": [
                "menu",
                "label"
              ]
            },
            "chapters": {
              "title": "Scene selection generated from the feature's chapters",
              "fields": [
                "position",
                "style",
                "image",
                "imageFocus",
                "perPage",
                "menu",
                "label"
              ],
              "required": [
                "label"
              ]
            },
            "home": {
              "title": "Jump straight to the root menu (a 'Home' / 'Main Menu' button)",
              "fields": [
                "position",
                "style",
                "image",
                "imageFocus",
                "label"
              ],
              "required": [
                "label"
              ]
            },
            "back": {
              "title": "Return to the previous menu",
              "fields": [
                "position",
                "style",
                "image",
                "imageFocus",
                "label"
              ],
              "required": [
                "label"
              ]
            }
          },
          "title": "Button"
        },
        "extra": {
          "fields": [
            {
              "name": "type",
              "required": true,
              "type": "enum",
              "enum": [
                "Clip",
                "Trailer",
                "BehindTheScenes",
                "DeletedScene",
                "Interview",
                "Scene",
                "Sample",
                "ThemeSong",
                "ThemeVideo",
                "Featurette",
                "Short",
                "Unknown"
              ],
              "description": "Jellyfin ExtraType (MediaBrowser.Model.Entities.ExtraType; verified against master for Jellyfin 12).",
              "label": "Kind of extra"
            },
            {
              "name": "durationSec",
              "required": true,
              "type": "number",
              "exclusiveMinimum": 0,
              "description": "Reference runtime in seconds. Primary matching signal.",
              "label": "Length (seconds)",
              "help": "How long the extra is. It is how the menu finds the right file."
            },
            {
              "name": "toleranceSec",
              "type": "number",
              "minimum": 0,
              "maximum": 120,
              "description": "Allowed +/- deviation. Default is renderer-defined (suggest 3s).",
              "label": "Allowed difference (seconds)",
              "default": 3
            },
            {
              "name": "ordinal",
              "type": "integer",
              "minimum": 1,
              "description": "1-based position among extras of the same type, sorted by duration. Tiebreaker only.",
              "label": "Number among extras of the same kind"
            },
            {
              "name": "optional",
              "type": "boolean",
              "description": "If true, a missing local match does not flag the menu as incomplete.",
              "label": "Fine if it is missing"
            }
          ],
          "title": "Extra",
          "create": {
            "type": "Featurette",
            "durationSec": 60
          }
        },
        "flow": {
          "fields": [
            {
              "name": "region",
              "required": true,
              "type": "object",
              "kind": "position",
              "requireAll": [
                "x",
                "y",
                "w",
                "h"
              ],
              "description": "The box the grid fills, e.g. the inside of a banner image.",
              "label": "Area the grid fills",
              "create": {
                "x": 10,
                "y": 30,
                "w": 80,
                "h": 60
              }
            },
            {
              "name": "columns",
              "required": true,
              "type": "integer",
              "minimum": 1,
              "maximum": 8,
              "label": "Columns"
            },
            {
              "name": "rows",
              "required": true,
              "type": "integer",
              "minimum": 1,
              "maximum": 12,
              "label": "Rows"
            },
            {
              "name": "moreLabel",
              "type": "string",
              "format": "label",
              "minLength": 1,
              "maxLength": 80,
              "pattern": "^[^<>]*$",
              "description": "Default: More.",
              "label": "Text of the More button",
              "default": "More"
            },
            {
              "name": "previousLabel",
              "type": "string",
              "format": "label",
              "minLength": 1,
              "maxLength": 80,
              "pattern": "^[^<>]*$",
              "description": "Default: Previous.",
              "label": "Text of the Previous button",
              "default": "Previous"
            }
          ],
          "title": "Automatic grid of buttons"
        },
        "layer": {
          "fields": [
            {
              "name": "type",
              "type": "enum",
              "enum": [
                "panel",
                "image"
              ],
              "required": true,
              "label": "Kind of layer"
            },
            {
              "name": "position",
              "required": true,
              "type": "object",
              "kind": "position",
              "description": "Where an element sits, as percentages of the menu screen so layouts scale to any display. x/y place the element's anchor point; w/h optionally size it.",
              "label": "Place on the screen",
              "create": {
                "x": 0,
                "y": 0,
                "w": 100,
                "h": 15
              }
            },
            {
              "name": "fill",
              "type": "string",
              "format": "color",
              "pattern": "^#[0-9a-fA-F]{6}$",
              "label": "Fill colour",
              "defaultValue": "#000000"
            },
            {
              "name": "opacity",
              "type": "number",
              "minimum": 0,
              "maximum": 1,
              "label": "Opacity (0 to 1)",
              "step": 0.05
            },
            {
              "name": "borderColor",
              "type": "string",
              "format": "color",
              "pattern": "^#[0-9a-fA-F]{6}$",
              "label": "Border colour",
              "defaultValue": "#ffffff"
            },
            {
              "name": "borderWidth",
              "type": "number",
              "minimum": 0,
              "maximum": 10,
              "description": "Percent of the screen height.",
              "label": "Border width (% of screen height)",
              "step": 0.1
            },
            {
              "name": "radius",
              "type": "number",
              "minimum": 0,
              "maximum": 50,
              "description": "Corner radius, percent of the screen height.",
              "label": "Corner rounding (% of screen height)",
              "step": 0.5
            },
            {
              "name": "image",
              "required": true,
              "type": "string",
              "format": "imageRef",
              "maxLength": 20000,
              "pattern": "^(https://[^\\s\"'()<>\\\\]+|data:image/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+|asset:[A-Za-z0-9][A-Za-z0-9._-]{0,63}(/[A-Za-z0-9][A-Za-z0-9._-]{0,63}){0,3})$",
              "description": "Artwork for a button. Never a file path. Either an https URL, a small inline data: URI for icons, or an asset:<folder>/<file> reference naming a file in the server's menu assets folder (the menu's own art, served by the plugin). Renderers draw it only via an image element, never as markup.",
              "label": "Picture"
            },
            {
              "name": "fit",
              "type": "enum",
              "enum": [
                "contain",
                "fill",
                "cover"
              ],
              "description": "contain (default) keeps the picture's proportions inside the box; fill stretches it; cover crops it to fill.",
              "label": "How the picture fills its box",
              "default": "contain"
            }
          ],
          "discriminator": "type",
          "variants": {
            "panel": {
              "title": "A flat panel (a bar or box behind the buttons)",
              "fields": [
                "position",
                "fill",
                "opacity",
                "borderColor",
                "borderWidth",
                "radius"
              ],
              "required": [
                "position"
              ]
            },
            "image": {
              "title": "A decorative image",
              "fields": [
                "position",
                "image",
                "fit",
                "opacity"
              ],
              "required": [
                "image",
                "position"
              ]
            }
          },
          "title": "Decorative layer"
        },
        "layout": {
          "fields": [
            {
              "name": "titlePosition",
              "type": "object",
              "kind": "position",
              "description": "Where an element sits, as percentages of the menu screen so layouts scale to any display. x/y place the element's anchor point; w/h optionally size it.",
              "label": "Where the title goes",
              "create": {
                "x": 50,
                "y": 8,
                "anchor": "top"
              }
            },
            {
              "name": "hideTitle",
              "type": "boolean",
              "label": "Hide the title"
            },
            {
              "name": "buttonStyle",
              "type": "enum",
              "enum": [
                "text",
                "frame",
                "glow",
                "arrow"
              ],
              "description": "Default for entries that don't set their own style.",
              "label": "Look of the buttons"
            },
            {
              "name": "flow",
              "type": "object",
              "kind": "flow",
              "description": "Automatic grid placement with paging. Entries that have no position of their own are laid out left-to-right, top-to-bottom inside the region. If they don't all fit, the renderer adds a More button (and Previous on later pages); 'back' entries stay on every page. A menu using flow must not also give entries positions.",
              "label": "Automatic grid of buttons",
              "create": {
                "region": {
                  "x": 10,
                  "y": 30,
                  "w": 80,
                  "h": 60
                },
                "columns": 2,
                "rows": 4
              }
            },
            {
              "name": "transition",
              "type": "object",
              "kind": "transition",
              "description": "Animation when moving between menus or pages. The background (including trailer video) and any layers shared by both screens stay put; the buttons and title animate. Ignored for viewers who prefer reduced motion.",
              "label": "Animation between pages",
              "create": {
                "style": "fade"
              }
            },
            {
              "name": "layers",
              "type": "array",
              "kind": "layer",
              "maxItems": 20,
              "description": "Decorative shapes and images drawn behind the buttons, in order (later layers on top). They are not focusable.",
              "label": "Decorative layers",
              "createItem": {
                "type": "panel",
                "position": {
                  "x": 0,
                  "y": 0,
                  "w": 100,
                  "h": 15
                },
                "fill": "#000000",
                "opacity": 0.6
              }
            }
          ],
          "title": "Layout"
        },
        "match": {
          "fields": [
            {
              "name": "itemType",
              "required": true,
              "type": "enum",
              "enum": [
                "Movie",
                "Series",
                "Season"
              ],
              "label": "Kind of title"
            },
            {
              "name": "seasonNumber",
              "type": "integer",
              "minimum": 0,
              "description": "Required when itemType is Season.",
              "label": "Season number",
              "help": "Needed when the kind of title is Season."
            },
            {
              "name": "providerIds",
              "required": true,
              "type": "object",
              "kind": "providerIds",
              "minProperties": 1,
              "label": "Provider ids",
              "create": {
                "Tmdb": ""
              }
            },
            {
              "name": "release",
              "type": "object",
              "kind": "release",
              "description": "Which physical release this menu describes. Extras differ between editions, so this disambiguates multiple menus for the same title.",
              "label": "Which release (edition, format...)",
              "create": {}
            }
          ],
          "title": "Which title this is for"
        },
        "menu": {
          "fields": [
            {
              "name": "title",
              "required": true,
              "type": "string",
              "format": "label",
              "minLength": 1,
              "maxLength": 80,
              "pattern": "^[^<>]*$",
              "description": "Plain text only. Renderers MUST insert as text (textContent), never as HTML.",
              "label": "Title"
            },
            {
              "name": "entries",
              "required": true,
              "type": "array",
              "kind": "entry",
              "minItems": 1,
              "maxItems": 50,
              "label": "Buttons"
            },
            {
              "name": "background",
              "type": "object",
              "kind": "background",
              "description": "Image references only; images are fetched locally at render time and never stored in the shared file.",
              "label": "Background (this page only)",
              "create": {
                "source": "jellyfin",
                "imageType": "Backdrop",
                "dim": 0.4
              }
            },
            {
              "name": "theme",
              "type": "object",
              "kind": "theme",
              "label": "Colours and text (this page only)",
              "create": {
                "id": "list-dark"
              }
            },
            {
              "name": "layout",
              "type": "object",
              "kind": "layout",
              "description": "Optional screen layout. Without it (or for entries with no position) buttons flow in a column.",
              "label": "Layout (this page only)",
              "create": {}
            },
            {
              "name": "audio",
              "type": "object",
              "kind": "audio",
              "label": "Music and sounds (this page only)",
              "create": {}
            }
          ],
          "title": "Page"
        },
        "meta": {
          "fields": [
            {
              "name": "author",
              "type": "string",
              "maxLength": 64,
              "label": "Author"
            },
            {
              "name": "language",
              "type": "string",
              "pattern": "^[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8})*$",
              "description": "BCP 47 language tag of the labels.",
              "label": "Language of the labels",
              "help": "A language code such as en or pt-BR."
            },
            {
              "name": "notes",
              "type": "string",
              "maxLength": 500,
              "label": "Notes"
            },
            {
              "name": "created",
              "type": "string",
              "label": "Created",
              "hidden": true
            },
            {
              "name": "updated",
              "type": "string",
              "label": "Updated",
              "hidden": true
            }
          ],
          "title": "About this menu"
        },
        "music": {
          "fields": [
            {
              "name": "source",
              "required": true,
              "type": "enum",
              "enum": [
                "file",
                "themeSong",
                "none"
              ],
              "label": "Music from"
            },
            {
              "name": "file",
              "type": "string",
              "format": "audioRef",
              "maxLength": 2000,
              "pattern": "^(https://[^\\s\"'()<>\\\\]+|asset:[A-Za-z0-9][A-Za-z0-9._-]{0,63}(/[A-Za-z0-9][A-Za-z0-9._-]{0,63}){0,3}\\.(mp3|ogg|opus|m4a|wav))$",
              "description": "For source=file.",
              "label": "Music file",
              "appliesTo": [
                "file"
              ]
            },
            {
              "name": "volume",
              "type": "number",
              "format": "volume",
              "minimum": 0,
              "maximum": 1,
              "description": "Default 0.5.",
              "label": "Volume (0 to 1)",
              "default": 0.5,
              "step": 0.05
            }
          ],
          "requiredWhen": {
            "field": "source",
            "values": {
              "file": [
                "file"
              ]
            }
          },
          "title": "Background music"
        },
        "position": {
          "fields": [
            {
              "name": "x",
              "required": true,
              "type": "number",
              "format": "percent",
              "minimum": 0,
              "maximum": 100,
              "label": "Across (%)",
              "step": 0.5
            },
            {
              "name": "y",
              "required": true,
              "type": "number",
              "format": "percent",
              "minimum": 0,
              "maximum": 100,
              "label": "Down (%)",
              "step": 0.5
            },
            {
              "name": "w",
              "type": "number",
              "format": "percent",
              "minimum": 0,
              "maximum": 100,
              "label": "Width (%)",
              "step": 0.5
            },
            {
              "name": "h",
              "type": "number",
              "format": "percent",
              "minimum": 0,
              "maximum": 100,
              "label": "Height (%)",
              "step": 0.5
            },
            {
              "name": "anchor",
              "type": "enum",
              "enum": [
                "top-left",
                "top",
                "top-right",
                "left",
                "center",
                "right",
                "bottom-left",
                "bottom",
                "bottom-right"
              ],
              "description": "Which point of the element x/y refers to. Default top-left.",
              "label": "Which point of the item is placed",
              "default": "top-left"
            }
          ],
          "title": "Place on the screen"
        },
        "providerIds": {
          "fields": [
            {
              "name": "Tmdb",
              "type": "string",
              "pattern": "^[0-9]+$",
              "label": "TMDB id"
            },
            {
              "name": "Imdb",
              "type": "string",
              "pattern": "^tt[0-9]{7,9}$",
              "label": "IMDB id"
            },
            {
              "name": "Tvdb",
              "type": "string",
              "pattern": "^[0-9]+$",
              "label": "TVDB id"
            }
          ],
          "title": "Provider ids"
        },
        "release": {
          "fields": [
            {
              "name": "edition",
              "type": "string",
              "maxLength": 80,
              "label": "Edition"
            },
            {
              "name": "format",
              "type": "enum",
              "enum": [
                "DVD",
                "BluRay",
                "UHD",
                "Digital",
                "Other"
              ],
              "label": "Format"
            },
            {
              "name": "region",
              "type": "string",
              "maxLength": 16,
              "label": "Region"
            },
            {
              "name": "year",
              "type": "integer",
              "minimum": 1900,
              "maximum": 2100,
              "label": "Release year"
            },
            {
              "name": "publisher",
              "type": "string",
              "maxLength": 80,
              "label": "Publisher"
            },
            {
              "name": "upc",
              "type": "string",
              "pattern": "^[0-9]{8,14}$",
              "label": "UPC (barcode)"
            }
          ],
          "title": "Which release"
        },
        "sounds": {
          "fields": [
            {
              "name": "preset",
              "type": "enum",
              "enum": [
                "none",
                "click",
                "chime",
                "beep"
              ],
              "label": "Built-in sounds"
            },
            {
              "name": "volume",
              "type": "number",
              "format": "volume",
              "minimum": 0,
              "maximum": 1,
              "description": "Default 0.5.",
              "label": "Volume (0 to 1)",
              "default": 0.5,
              "step": 0.05
            },
            {
              "name": "move",
              "type": "string",
              "format": "audioRef",
              "maxLength": 2000,
              "pattern": "^(https://[^\\s\"'()<>\\\\]+|asset:[A-Za-z0-9][A-Za-z0-9._-]{0,63}(/[A-Za-z0-9][A-Za-z0-9._-]{0,63}){0,3}\\.(mp3|ogg|opus|m4a|wav))$",
              "description": "Played when the highlight moves.",
              "label": "Sound file when moving"
            },
            {
              "name": "select",
              "type": "string",
              "format": "audioRef",
              "maxLength": 2000,
              "pattern": "^(https://[^\\s\"'()<>\\\\]+|asset:[A-Za-z0-9][A-Za-z0-9._-]{0,63}(/[A-Za-z0-9][A-Za-z0-9._-]{0,63}){0,3}\\.(mp3|ogg|opus|m4a|wav))$",
              "description": "Played when a button is activated.",
              "label": "Sound file when choosing"
            },
            {
              "name": "back",
              "type": "string",
              "format": "audioRef",
              "maxLength": 2000,
              "pattern": "^(https://[^\\s\"'()<>\\\\]+|asset:[A-Za-z0-9][A-Za-z0-9._-]{0,63}(/[A-Za-z0-9][A-Za-z0-9._-]{0,63}){0,3}\\.(mp3|ogg|opus|m4a|wav))$",
              "description": "Played when going back or home.",
              "label": "Sound file when going back"
            }
          ],
          "title": "Button sounds"
        },
        "theme": {
          "fields": [
            {
              "name": "id",
              "required": true,
              "type": "string",
              "pattern": "^[a-z0-9-]{1,32}$",
              "description": "Built-in theme/layout name shipped with the renderer. Unknown ids fall back to the default.",
              "label": "Theme name"
            },
            {
              "name": "accent",
              "type": "string",
              "format": "color",
              "pattern": "^#[0-9a-fA-F]{6}$",
              "description": "Highlight colour of the focused button.",
              "label": "Highlight colour",
              "defaultValue": "#00a4dc"
            },
            {
              "name": "textColor",
              "type": "string",
              "format": "color",
              "pattern": "^#[0-9a-fA-F]{6}$",
              "description": "Button text colour when not highlighted. Default white.",
              "label": "Button text colour",
              "default": "white",
              "defaultValue": "#ffffff"
            },
            {
              "name": "font",
              "type": "enum",
              "enum": [
                "sans",
                "serif",
                "condensed",
                "wide",
                "mono"
              ],
              "description": "A built-in font family. Arbitrary font names are not accepted.",
              "label": "Font"
            },
            {
              "name": "fontSize",
              "type": "number",
              "minimum": 1,
              "maximum": 10,
              "description": "Button text size as percent of the screen height, so it scales with the display.",
              "label": "Text size (% of screen height)",
              "step": 0.1
            },
            {
              "name": "align",
              "type": "enum",
              "enum": [
                "left",
                "center",
                "right"
              ],
              "label": "Text alignment"
            },
            {
              "name": "uppercase",
              "type": "boolean",
              "label": "Capital letters"
            },
            {
              "name": "bold",
              "type": "boolean",
              "label": "Bold"
            },
            {
              "name": "letterSpacing",
              "type": "number",
              "minimum": 0,
              "maximum": 1,
              "description": "Extra spacing between letters, in em.",
              "label": "Letter spacing (em)",
              "step": 0.01
            }
          ],
          "title": "Colours and text"
        },
        "transition": {
          "fields": [
            {
              "name": "style",
              "required": true,
              "type": "enum",
              "enum": [
                "none",
                "fade",
                "slide",
                "rise",
                "zoom",
                "wipe"
              ],
              "label": "Animation"
            },
            {
              "name": "durationMs",
              "type": "integer",
              "minimum": 0,
              "maximum": 2000,
              "description": "Default 300.",
              "label": "How long (milliseconds)",
              "default": 300
            }
          ],
          "title": "Animation between pages"
        }
      }
    };
});
