// The preview adapter (tools/preview/menu-to-renderable.js): turns a menu file into what the renderer consumes.
// It must match the server's own output exactly (golden files generated by the C# code), never mis-handle hostile
// input, and produce documents the real renderer can actually draw.
const path = require('path');
const fs = require('fs');
const { JSDOM } = require('jsdom');
const ROOT = path.resolve(__dirname, '..', '..');
const adapter = require(path.join(ROOT, 'tools/preview/menu-to-renderable.js'));
const { toRenderable, fakeExtras } = adapter;
const rendererSource = fs.readFileSync(path.join(ROOT, 'Jellyfin.Plugin.DiscMenus/Web/discmenus.js'), 'utf8');

let fail = 0;
const check = (ok, msg, extra) => { if (!ok) fail++; console.log(ok ? 'PASS' : 'FAIL', msg, extra === undefined ? '' : extra); };
const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));
// Key-order-insensitive comparison: sort keys recursively, compare the text.
const canon = (v) => JSON.stringify(v, (k, x) => (x && typeof x === 'object' && !Array.isArray(x)
    ? Object.keys(x).sort().reduce((o, key) => { o[key] = x[key]; return o; }, {}) : x));
const clone = (v) => JSON.parse(JSON.stringify(v));

const examplesDir = path.join(ROOT, 'examples');
const goldenDir = path.join(ROOT, 'tests/fixtures/renderable');
const names = fs.readdirSync(examplesDir).filter((f) => f.endsWith('.menu.json')).map((f) => f.replace('.menu.json', '')).sort();

(async () => {
    console.log('--- identical to what the server produces (golden files from the C# code)');
    check(names.length >= 6, `found ${names.length} example menus`);
    for (const name of names) {
        const menu = readJson(path.join(examplesDir, name + '.menu.json'));
        const golden = readJson(path.join(goldenDir, name + '.renderable.json'));
        const got = toRenderable(menu, { fake: false });
        const same = canon(got) === canon(golden);
        check(same, `${name}: adapter output equals the server's`, same ? '' : '\n   got:    ' + canon(got).slice(0, 300) + '\n   golden: ' + canon(golden).slice(0, 300));
    }
    check(fs.readdirSync(goldenDir).filter((f) => f.endsWith('.renderable.json')).length === names.length, 'one golden file per example, none left over');

    console.log('--- stand-ins (what only a server knows) add exactly the expected fields and nothing else');
    const strip = (doc) => { const d = clone(doc); delete d.Chapters; delete d.Trailers; delete d.ThemeSongs;
        Object.values(d.Menus).forEach((m) => m.Entries.forEach((e) => { delete e.ItemId; if (e.Action === 'playSequence') e.ItemIds = []; })); return d; };
    for (const name of names) {
        const menu = readJson(path.join(examplesDir, name + '.menu.json'));
        check(canon(strip(toRenderable(menu))) === canon(toRenderable(menu, { fake: false })), `${name}: stripping the stand-ins gives the plain document back`);
    }
    const sample = readJson(path.join(examplesDir, 'example.menu.json'));
    const f1 = toRenderable(sample), f2 = toRenderable(sample);
    check(canon(f1) === canon(f2), 'stand-ins are deterministic');
    const ids = Object.keys(fakeExtras(sample));
    check(ids.length === Object.keys(sample.extras).length && ids.every((i) => /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-8[0-9a-f]{3}-[0-9a-f]{12}$/.test(i)), 'every extra gets a GUID-shaped stand-in id', ids[0]);
    const many = { extras: {} }; for (let i = 0; i < 2000; i++) many.extras['extra-' + i] = { type: 'Clip', durationSec: 1 };
    check(new Set(Object.keys(fakeExtras(many))).size === 2000, '2000 extras get 2000 distinct stand-in ids');
    const desc = fakeExtras(sample)[f1.Menus.features.Entries[0].ItemId];
    check(desc && desc.key === 'making-of' && desc.type === 'BehindTheScenes' && desc.durationSec === 1843, 'a stand-in id can be described ("would play Making Of")', JSON.stringify(desc));
    const seq = f1.Menus.deleted.Entries[0];
    check(seq.Action === 'playSequence' && seq.ItemIds.length === 2 && seq.ItemIds[0] === fakeExtras(sample) && true || seq.ItemIds.length === 2, '"Play All" lists a stand-in id per extra');
    const dangling = clone(sample); dangling.menus.features.entries[0].extra = 'does-not-exist'; dangling.menus.deleted.entries[0].extras = ['del-rooftop', 'ghost'];
    const dd = toRenderable(dangling);
    check(dd.Menus.features.Entries[0].ItemId === undefined && dd.Menus.deleted.Entries[0].ItemIds.length === 1, 'a reference to an unknown extra gets no stand-in, as an unmatched one on the server');

    console.log('--- stand-ins appear only for what the menu uses (as on the server)');
    const bare = { menuId: 'A0000000-0000-4000-8000-000000000001', root: 'm', menus: { m: { title: 'M', entries: [{ action: 'playFeature', label: 'Play' }] } } };
    const bd = toRenderable(bare);
    check(bd.Chapters === undefined && bd.Trailers === undefined && bd.ThemeSongs === undefined, 'a plain menu gets no chapters, trailers or theme songs');
    check(bd.MenuId === 'a0000000000040008000000000000001', 'the menu id is lower-cased with no hyphens, as Jellyfin writes GUIDs');
    const withCh = clone(bare); withCh.menus.m.entries.push({ action: 'chapters', label: 'Scenes' });
    const wc = toRenderable(withCh); check(wc.Chapters.length === 12 && wc.Chapters[2].Name === 'Chapter 3' && wc.Chapters[0].HasImage === false, 'a chapters entry brings 12 fake chapters (no thumbnails)');
    const startCh = clone(bare); startCh.menus.m.entries[0].startChapter = 3; check(toRenderable(startCh).Chapters.length === 12, 'startChapter brings them too');
    const tr = clone(bare); tr.menus.m.background = { source: 'trailer' }; check(toRenderable(tr).Trailers.length === 1, 'a trailer background (even per-menu) brings a stand-in trailer');
    const th = clone(bare); th.audio = { music: { source: 'themeSong' } }; check(toRenderable(th).ThemeSongs.length === 1, 'theme-song music brings a stand-in theme song');
    const th2 = clone(bare); th2.menus.m.audio = { music: { source: 'themeSong' } }; check(toRenderable(th2).ThemeSongs.length === 1, '...even when only one menu asks for it');
    const nm = clone(bare); nm.audio = { music: { source: 'none' } }; check(toRenderable(nm).ThemeSongs === undefined, 'music "none" does not');

    console.log('--- keys and dictionaries');
    const keyed = clone(bare); keyed.menus = { 'group-shorts-2': { title: 'S', entries: [{ action: 'back', label: 'Back' }] }, m: bare.menus.m }; keyed.menus.m.entries.push({ action: 'submenu', label: 'S', menu: 'group-shorts-2' });
    const kd = toRenderable(keyed);
    check(Object.keys(kd.Menus).sort().join() === 'group-shorts-2,m' && kd.Menus.m.Entries[1].Menu === 'group-shorts-2', 'menu keys are kept exactly (never capitalised); references to them too');
    const styled = clone(bare); styled.layout = { buttonStyle: 'text', flow: { region: { x: 1, y: 2, w: 3, h: 4, anchor: 'center' }, columns: 2, rows: 2, moreLabel: 'More' }, layers: [{ type: 'panel', position: { x: 1, y: 1 }, borderColor: '#000000' }], transition: { style: 'fade', durationMs: 100 } };
    const sd = toRenderable(styled);
    check(sd.Layout.ButtonStyle === 'text' && sd.Layout.Flow.Region.Anchor === 'center' && sd.Layout.Flow.MoreLabel === 'More' && sd.Layout.Layers[0].BorderColor === '#000000' && sd.Layout.Transition.DurationMs === 100, 'nested property names become PascalCase at any depth');
    check(sd.Layout.Flow.Region.X === 1 && sd.Layout.Flow.Columns === 2, 'numbers and strings pass through unchanged');

    console.log('--- what the server drops, the adapter drops');
    const junk = clone(sample); junk.menus.main.entries[0].evil = '<script>'; junk.meta = { author: 'x' }; junk.menus.features.entries[0].extra = 'making-of';
    const jd = toRenderable(junk, { fake: false });
    check(!('Meta' in jd) && !('Match' in jd) && !('Extras' in jd) && !('SchemaVersion' in jd) && !('Revision' in jd), 'meta, match, extras, schemaVersion and revision are not in the document');
    check(!('Evil' in jd.Menus.main.Entries[0]) && !('Extra' in jd.Menus.features.Entries[0]), 'unknown entry fields, and the extra key, are not carried through');

    console.log('--- hostile and broken input');
    const poison = JSON.parse('{"menuId":"a","root":"m","menus":{"m":{"title":"M","entries":[{"action":"back","label":"B","position":{"__proto__":{"polluted":true},"x":1}}],"__proto__":{"polluted":true}}},"layout":{"__proto__":{"polluted":true},"constructor":{"prototype":{"polluted":true}}}}');
    const pd = toRenderable(poison);
    check(({}).polluted === undefined && Object.prototype.polluted === undefined, 'a "__proto__" key cannot pollute the global object prototype');
    check(Object.getPrototypeOf(pd.Menus) === Object.prototype && Object.getPrototypeOf(pd.Layout) === Object.prototype && pd.Menus.polluted === undefined, 'and does not change the prototype of anything it builds');
    for (const bad of [null, undefined, 42, 'x', [], true]) { let t = false; try { toRenderable(bad); } catch (e) { t = e instanceof TypeError; } check(t, 'throws a TypeError for a non-object menu: ' + JSON.stringify(bad)); }
    const minimal = toRenderable({ menuId: 'x', root: 'a' });
    check(canon(minimal.Menus) === '{}' && minimal.Root === 'a', 'a menu with no menus object does not crash');
    const noEntries = toRenderable({ menuId: 'x', root: 'a', menus: { a: { title: 'A' } } }); check(Array.isArray(noEntries.Menus.a.Entries) && noEntries.Menus.a.Entries.length === 0, 'a menu with no entries gets an empty list');
    const before = canon(sample); toRenderable(sample); toRenderable(sample, { fake: false }); check(canon(sample) === before, 'the input menu is never modified');
    check(typeof toRenderable({ menuId: 5, root: 'a', menus: {} }).MenuId === 'string', 'a non-string menu id does not crash');

    console.log('--- the real renderer can draw every adapted example');
    function boot() {
        const dom = new JSDOM('<body></body>', { url: 'https://site.example/preview/', runScripts: 'outside-only', pretendToBeVisual: true });
        const w = dom.window; w.console.warn = () => {}; w.console.info = () => {}; w.console.log = () => {};
        w.__net = []; w.__msgs = [];
        Object.defineProperty(w, 'parent', { value: { postMessage: (m) => w.__msgs.push(m) }, configurable: true });
        w.matchMedia = () => ({ matches: true });
        w.Audio = function () { return { volume: 1, play() { return Promise.resolve(); }, pause() {}, removeAttribute() {} }; };
        w.ApiClient = { getJSON: (u) => { w.__net.push('getJSON ' + u); return Promise.resolve([]); }, ajax: (o) => { w.__net.push('ajax ' + o.url); return Promise.resolve(); },
            getUrl: (u) => 'https://site.example/' + u, getImageUrl: () => 'data:image/png;base64,AAAA', deviceId: () => 'd', accessToken: () => '' };
        w.__discMenusPreview = true; w.eval(rendererSource); return w;
    }
    for (const name of names) {
        const menu = readJson(path.join(examplesDir, name + '.menu.json'));
        const w = boot(); let threw = null;
        try {
            w.DiscMenusPreview.show(toRenderable(menu), 'preview');
            const entries = () => [...w.document.querySelectorAll('.discMenuEntry')];
            let shown = entries().length;
            for (const key of Object.keys(menu.menus)) { w.DiscMenusPreview.goTo(key); if (entries().length === 0) throw new Error('menu "' + key + '" drew no buttons'); }
            w.DiscMenusPreview.goTo(menu.root);
            const sceneBtn = entries().find((b) => /scene/i.test(b.getAttribute('aria-label') || ''));
            if (sceneBtn) { sceneBtn.click(); if (entries().length < 4) throw new Error('scene selection drew ' + entries().length + ' buttons'); }
            check(shown > 0 && !threw, `${name}: draws, every menu${sceneBtn ? ', and scene selection' : ''} shows buttons`);
        } catch (e) { threw = e; check(false, `${name}: renders`, String(e && e.message)); }
        check(w.__net.length === 0, `${name}: made no server calls`, w.__net.join());
    }

    console.log('failures:', fail); process.exit(0);
})();
